# Generated by Django 2.1.3 on 2018-12-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='cached_data',
            field=models.FileField(blank=True, help_text='A copy of the image data from which we can generate scaled representations.', null=True, upload_to='cached-images'),
        ),
    ]
