# Generated by Django 2.1.4 on 2018-12-12 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0002_image_cached_data"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="scanned",
            new_name="retrieved",
        ),
    ]
