# Generated by Django 2.1.4 on 2019-01-20 11:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0005_image_represention_upload_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="data_url",
            field=models.URLField(max_length=4000, unique=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="media_type",
            field=models.CharField(
                blank=True,
                max_length=4000,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^(image|application)/\\w+(;\\s*\\w+=.*)?$"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="representation",
            name="media_type",
            field=models.CharField(
                max_length=4000,
                validators=[
                    django.core.validators.RegexValidator(
                        "^(image|application)/\\w+(;\\s*\\w+=.*)?$"
                    )
                ],
            ),
        ),
    ]
