# Generated by Django 2.1.7 on 2019-03-14 21:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0006_embiggen_text_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="media_type",
            field=models.CharField(
                blank=True,
                max_length=4000,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^(image|application)/[\\w.+-]+(;\\s*\\w+=.*)?$"
                    )
                ],
            ),
        ),
    ]
