# Generated by Django 3.0.8 on 2020-08-30 21:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0018_locator_sensitive"),
        ("mentions", "0002_add_incoming"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="incoming",
            options={
                "verbose_name": "incoming mention",
                "verbose_name_plural": "incoming mentions",
            },
        ),
        migrations.AlterModelOptions(
            name="locatorreceiver",
            options={
                "verbose_name": "locator receiver",
                "verbose_name_plural": "locator receivers",
            },
        ),
        migrations.AlterModelOptions(
            name="outgoing",
            options={
                "verbose_name": "outgoing mention",
                "verbose_name_plural": "outgoing mentions",
            },
        ),
        migrations.AlterModelOptions(
            name="receiver",
            options={"verbose_name": "receiver", "verbose_name_plural": "receivers"},
        ),
        migrations.AlterField(
            model_name="incoming",
            name="created",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="created"
            ),
        ),
        migrations.AlterField(
            model_name="incoming",
            name="source",
            field=models.ForeignKey(
                blank=True,
                help_text="Location of a post that mentions one of our notes, if known.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="notes.Locator",
                verbose_name="source",
            ),
        ),
        migrations.AlterField(
            model_name="incoming",
            name="source_url",
            field=models.URLField(
                help_text="URL of a page mentioning oine of our notes, as supplied by caller.",
                max_length=4000,
                verbose_name="source URL",
            ),
        ),
        migrations.AlterField(
            model_name="incoming",
            name="target",
            field=models.ForeignKey(
                blank=True,
                help_text="The note that is mentioned by the source, if known.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="notes.Note",
                verbose_name="target",
            ),
        ),
        migrations.AlterField(
            model_name="incoming",
            name="target_url",
            field=models.URLField(
                help_text="URL of one of our notes, as supplied by caller.",
                max_length=4000,
                verbose_name="targeet URL",
            ),
        ),
        migrations.AlterField(
            model_name="incoming",
            name="user_agent",
            field=models.CharField(
                blank=True,
                help_text="What software the caller claims to be running.",
                max_length=4000,
                null=True,
                verbose_name="user agent",
            ),
        ),
        migrations.AlterField(
            model_name="locatorreceiver",
            name="created",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="created"
            ),
        ),
        migrations.AlterField(
            model_name="locatorreceiver",
            name="locator",
            field=models.OneToOneField(
                help_text="Locator that is associated with receiver.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mentions_info",
                to="notes.Locator",
                verbose_name="locator",
            ),
        ),
        migrations.AlterField(
            model_name="locatorreceiver",
            name="receiver",
            field=models.ForeignKey(
                blank=True,
                help_text="Receiver handling mentions targeting the locator.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="associated_locators",
                related_query_name="associated_locator",
                to="mentions.Receiver",
                verbose_name="receiver",
            ),
        ),
        migrations.AlterField(
            model_name="outgoing",
            name="created",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="created"
            ),
        ),
        migrations.AlterField(
            model_name="outgoing",
            name="discovered",
            field=models.DateTimeField(
                blank=True,
                help_text="When the discovery phase of WebMention protocol concluded (successfully or otherwise).",
                null=True,
                verbose_name="discovered",
            ),
        ),
        migrations.AlterField(
            model_name="outgoing",
            name="notified",
            field=models.DateTimeField(
                blank=True,
                help_text="When the notification of the receiver concluded (successfully or otherwise)",
                null=True,
                verbose_name="notified",
            ),
        ),
        migrations.AlterField(
            model_name="outgoing",
            name="receiver",
            field=models.ForeignKey(
                blank=True,
                help_text="Receiver used when notifying this locator.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mentions.Receiver",
                verbose_name="receiver",
            ),
        ),
        migrations.AlterField(
            model_name="outgoing",
            name="response_status",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="HTTP status code returned by receiver when notified.",
                null=True,
                verbose_name="response status",
            ),
        ),
        migrations.AlterField(
            model_name="outgoing",
            name="source",
            field=models.ForeignKey(
                help_text="Mentions an external resource.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outgoing_mentions",
                related_query_name="outgoing_mention",
                to="notes.Note",
                verbose_name="source",
            ),
        ),
        migrations.AlterField(
            model_name="outgoing",
            name="target",
            field=models.ForeignKey(
                help_text="External resource mentioned in this note.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outgoing_mentions",
                related_query_name="outgoing_mention",
                to="notes.Locator",
                verbose_name="target",
            ),
        ),
        migrations.AlterField(
            model_name="receiver",
            name="created",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="created"
            ),
        ),
        migrations.AlterField(
            model_name="receiver",
            name="url",
            field=models.URLField(max_length=4000, unique=True, verbose_name="URL"),
        ),
    ]
