# Generated by Django 3.0.5 on 2020-06-28 15:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes', '0017_auto_20200621_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Domain name of the Mastodon instance.', max_length=255, verbose_name='domain name')),
                ('client_id', models.CharField(help_text='Supplied by Mastodon instance when entrolling the app.', max_length=255, verbose_name='client ID')),
                ('client_secret', models.CharField(help_text='Supplied by Mastodon instance when entrolling the app.', max_length=255, verbose_name='client secret')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
            ],
            options={
                'verbose_name': 'server',
                'verbose_name_plural': 'servers',
            },
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of user on that instance (without the @ signs and without the domain name)', max_length=255, verbose_name='name')),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('expires_at', models.BigIntegerField(blank=True, help_text='When the access token expires, in seconds since 1970-01-01', null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.Series', verbose_name='series')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mastodon.Server', verbose_name='server')),
            ],
            options={
                'verbose_name': 'connection',
                'verbose_name_plural': 'connections',
                'unique_together': {('series', 'server', 'name')},
            },
        ),
    ]
