# Generated by Django 3.0.5 on 2020-06-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastodon', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='posted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='posted'),
        ),
    ]
