Title: About

# About this&nbsp;site

**{{ series.title|default:"Ooble" }}** is a microblogging site for publishing
links to interesting, fun, or informative web pages.

Part of the reason creating our own site is that without advertising we have
no need for intrusive tracking of our readers.

This is very much a work in progress. The longer-term plan is to integrate it
with IndieWeb social linking and syndicate to Twitter and Tumblr to people can
follow Ooble sites with a minimum of friction.
