Title: Privacy policy

# Privacy policy

This site is not funded by advertising.

We do not store personal data about our readers or track our readers’ visits.

We do not store cookies on readers’ browsers; site editors and admins will need
cookies to log in.

When your browser requests pages it tells the server the IP address you are
using to access the internet. We don’t at present but might in future use this
information to debug technical problems, to fight spam, or as required to
fulfil legal obligations.
