Title: Privacy policy

# Privacy policy

We do not store personal data about our readers or track our readers’ visits.

We do not store [cookies][] on readers’ browsers. Site editors and admins, on
the other hand, will need cookies to log in.

When your browser requests pages it tells the server the IP address you are
using to access the internet. We don’t at present but might in future use this
information to debug technical problems, to fight spam, or as required to
fulfil legal obligations.

This site is not funded by advertising.

  [cookies]: https://en.wikipedia.org/wiki/HTTP_cookie
