# Generated by Django 2.1.3 on 2018-12-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locator',
            name='scanned',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
