# Generated by Django 2.1.4 on 2018-12-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_image_retrieved'),
        ('notes', '0002_locator_scanned'),
    ]

    operations = [
        migrations.AddField(
            model_name='locator',
            name='images',
            field=models.ManyToManyField(to='images.Image'),
        ),
    ]
