# Generated by Django 2.1.4 on 2019-01-28 22:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0004_embiggen_text_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.SlugField(
                        help_text="Internal name of the tag, as lowercase words separated by dashes.",
                        max_length=4000,
                        unique=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Conventional capitalization of this tag, as words separated by spaces.",
                        max_length=4000,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["label"],
            },
        ),
        migrations.AddField(
            model_name="note",
            name="tags",
            field=models.ManyToManyField(
                related_name="occurences",
                related_query_name="occurrence",
                to="notes.Tag",
            ),
        ),
    ]
