# Generated by Django 2.1.7 on 2019-03-23 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0009_copy_locator_legacy_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="locator",
            name="legacy_images",
        ),
    ]
