# Generated by Django 2.2 on 2019-04-22 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0007_validate_media_type"),
        ("notes", "0011_locator_via"),
    ]

    operations = [
        migrations.AddField(
            model_name="series",
            name="icon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="images.Image",
            ),
        ),
    ]
