# Generated by Django 3.0.5 on 2020-05-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0013_series_apple_touch_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='slug',
            field=models.SlugField(blank=True, help_text='Identifies profile page for this person.', max_length=64, null=True, unique=True),
        ),
    ]
