# Generated by Django 3.0.5 on 2020-05-04 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0014_person_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
