# Generated by Django 3.0.5 on 2020-05-17 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0007_validate_media_type"),
        ("notes", "0015_person_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="image",
            field=models.ForeignKey(
                blank=True,
                help_text="Depicts this user.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="images.Image",
            ),
        ),
    ]
